Repository 10Jojojojo/10Team, pull requests merged in 2023-10, with the labels that each got.

#2 [FEAT] : ⚙️구글 맵 지도 표시, 구글 Place API 받아오기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/footprint/app/MainActivity.kt
  app/src/main/java/com/footprint/app/api/NetWorkClient.kt
  app/src/main/java/com/footprint/app/api/NetWorkInterface.kt
  app/src/main/java/com/footprint/app/api/model/PlaceModel.kt
  app/src/main/java/com/footprint/app/api/serverdata/PlaceData.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModel.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModelFactory.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: enhancement

#7 [FEAT][Refactor] : ⚙️ 구글 Place API를 이용해 장소 데이터 지도에 뿌려주기, 프래그먼트 코드 리팩토링
  app/src/main/java/com/footprint/app/api/NetWorkInterface.kt
  app/src/main/java/com/footprint/app/api/model/PlaceModel.kt
  app/src/main/java/com/footprint/app/ui/community/CommunityFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModel.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_marker_hospital.png
  app/src/main/res/drawable/ic_marker_shop.png
Labels: FEAT, REFACTOR

#12 [Refactor] : 코드 리팩토링
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/footprint/app/MainActivity.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/themes.xml
Labels: REFACTOR

#14 [DESIGN] 마이페이지 UI 틀 잡기 및 수정 페이지로 이동 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/footprint/app/ui/home/HomeViewModel.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/footprint/app/ui/mypage_revise/MyPage_reviseFragment.kt
  app/src/main/res/drawable/background.xml
  app/src/main/res/drawable/ic_pen.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_page_revise.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: FEAT, UI

#17 [UI] : Splash 화면 초기 세팅
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/footprint/app/SplashActivity.kt
  app/src/main/res/anim/anim_splash.xml
  app/src/main/res/anim/anim_splash10.xml
  app/src/main/res/anim/anim_splash2.xml
  app/src/main/res/anim/anim_splash3.xml
  app/src/main/res/anim/anim_splash4.xml
  app/src/main/res/anim/anim_splash5.xml
  app/src/main/res/anim/anim_splash6.xml
  app/src/main/res/anim/anim_splash7.xml
  app/src/main/res/anim/anim_splash8.xml
  app/src/main/res/anim/anim_splash9.xml
  app/src/main/res/drawable/ic_splash_1.png
  app/src/main/res/drawable/ic_splash_10.png
  app/src/main/res/drawable/ic_splash_2.png
  app/src/main/res/drawable/ic_splash_3.png
  app/src/main/res/drawable/ic_splash_4.png
  app/src/main/res/drawable/ic_splash_5.png
  app/src/main/res/drawable/ic_splash_6.png
  app/src/main/res/drawable/ic_splash_7.png
  app/src/main/res/drawable/ic_splash_8.png
  app/src/main/res/drawable/ic_splash_9.png
  app/src/main/res/layout/activity_splash.xml
Labels: UI

#23 Dev
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/footprint/app/MainActivity.kt
  app/src/main/java/com/footprint/app/SplashActivity.kt
  app/src/main/java/com/footprint/app/api/NetWorkClient.kt
  app/src/main/java/com/footprint/app/api/NetWorkInterface.kt
  app/src/main/java/com/footprint/app/api/model/PlaceModel.kt
  app/src/main/java/com/footprint/app/api/serverdata/PlaceData.kt
  app/src/main/java/com/footprint/app/ui/community/CommunityFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModel.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModelFactory.kt
  app/src/main/java/com/footprint/app/ui/login/LoginActivity.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/footprint/app/ui/mypage_revise/MyPage_reviseFragment.kt
  app/src/main/res/anim/anim_splash.xml
  app/src/main/res/anim/anim_splash10.xml
  app/src/main/res/anim/anim_splash2.xml
  app/src/main/res/anim/anim_splash3.xml
  app/src/main/res/anim/anim_splash4.xml
  app/src/main/res/anim/anim_splash5.xml
  app/src/main/res/anim/anim_splash6.xml
  app/src/main/res/anim/anim_splash7.xml
  app/src/main/res/anim/anim_splash8.xml
  app/src/main/res/anim/anim_splash9.xml
  app/src/main/res/drawable/background.xml
  app/src/main/res/drawable/ic_marker_hospital.png
  app/src/main/res/drawable/ic_marker_shop.png
  app/src/main/res/drawable/ic_pen.png
  app/src/main/res/drawable/ic_splash_1.png
  app/src/main/res/drawable/ic_splash_10.png
  app/src/main/res/drawable/ic_splash_2.png
  app/src/main/res/drawable/ic_splash_3.png
  app/src/main/res/drawable/ic_splash_4.png
  app/src/main/res/drawable/ic_splash_5.png
  app/src/main/res/drawable/ic_splash_6.png
  app/src/main/res/drawable/ic_splash_7.png
  app/src/main/res/drawable/ic_splash_8.png
  app/src/main/res/drawable/ic_splash_9.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page_revise.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: FEAT

#24 [Feat] 서비스 적용된 산책 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/footprint/app/MainActivity.kt
  app/src/main/java/com/footprint/app/services/MyService.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModel.kt
  app/src/main/res/drawable/home_dialog_button_bgselector.xml
  app/src/main/res/drawable/home_dialog_button_text_color.xml
  app/src/main/res/drawable/home_dialog_root_bg.xml
  app/src/main/res/drawable/home_fragment_bottombar_bg.xml
  app/src/main/res/drawable/ic_pause.png
  app/src/main/res/drawable/ic_pawprint_off.png
  app/src/main/res/drawable/ic_pawprint_on.png
  app/src/main/res/drawable/ic_play.png
  app/src/main/res/drawable/ic_square.png
  app/src/main/res/layout/dialog_home_walkstop.xml
  app/src/main/res/layout/fragment_home.xml
Labels: FEAT

#26 Feat/mypage 기능구현
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/footprint/app/ProfileActivity.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyDogAdapter.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyDogFragment.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPage_reviseFragment.kt
  app/src/main/java/com/footprint/app/ui/mypage_revise/MyPage_reviseFragment.kt
  app/src/main/res/drawable/ic_plus.png
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_my_dog.xml
  app/src/main/res/layout/fragment_my_page_revise.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/mydogpluscard.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: FEAT, UI

#28 Feat/dogpage 기눙추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/footprint/app/ProfileActivity.kt
  app/src/main/java/com/footprint/app/SplashActivity.kt
  app/src/main/java/com/footprint/app/membershipActivity.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyDogAdapter.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyDogFragment.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPage_reviseFragment.kt
  app/src/main/res/layout/activity_membership.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_my_dog.xml
  app/src/main/res/layout/fragment_my_page_revise.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/mydogpluscard.xml
  app/src/main/res/values/colors.xml
Labels: FEAT

#31 [Feat] : 지도에 마커 표시 구현
  app/build.gradle.kts
  app/src/main/java/com/footprint/app/MainActivity.kt
  app/src/main/java/com/footprint/app/api/model/FlagModel.kt
  app/src/main/java/com/footprint/app/api/model/WalkModel.kt
  app/src/main/java/com/footprint/app/services/MyService.kt
  app/src/main/java/com/footprint/app/ui/home/FavoriteAdapter.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFavoriteFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeStopFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModel.kt
  app/src/main/java/com/footprint/app/util/ItemClick.kt
  app/src/main/java/com/footprint/app/util/SharedPref.kt
  app/src/main/res/color/bottom_navigation_colors.xml
  app/src/main/res/drawable/ic_favorite.png
  app/src/main/res/drawable/ic_flag.png
  app/src/main/res/drawable/ic_flag_blue.png
  app/src/main/res/drawable/ic_flag_green.png
  app/src/main/res/drawable/ic_flag_purple.png
  app/src/main/res/drawable/ic_flag_yellow.png
  app/src/main/res/drawable/ic_pawprint.png
  app/src/main/res/drawable/ic_pawprint_off.png
  app/src/main/res/drawable/ic_pawprint_on.png
  app/src/main/res/drawable/ic_settings.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_home_flag.xml
  app/src/main/res/layout/dialog_home_walkstop.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_favorite.xml
  app/src/main/res/layout/fragment_home_stop.xml
  app/src/main/res/layout/walkitem.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
Labels: FEAT

#41 [Refactor] : API키 받아오는 방식 수정, 갤러리 권한 요청 코드 수정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/footprint/app/MainActivity.kt
  app/src/main/java/com/footprint/app/api/NetWorkClient.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModel.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPage_reviseFragment.kt
Labels: REFACTOR

#49 [Feat][UI][Refactor]
  app/build.gradle.kts
  app/src/main/java/com/footprint/app/Constants.kt
  app/src/main/java/com/footprint/app/api/model/ProfileModel.kt
  app/src/main/java/com/footprint/app/api/model/WalkModel.kt
  app/src/main/java/com/footprint/app/membershipActivity.kt
  app/src/main/java/com/footprint/app/ui/home/FavoriteAdapter.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFavoriteFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFavoriteItemFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeStopFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModel.kt
  app/src/main/java/com/footprint/app/ui/mypage/MyPage_reviseFragment.kt
  app/src/main/res/drawable/dummy_petimage.png
  app/src/main/res/drawable/image_cryingdog.png
  app/src/main/res/layout/activity_membership.xml
  app/src/main/res/layout/dialog_home_walk.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_favorite.xml
  app/src/main/res/layout/fragment_home_favorite_item.xml
  app/src/main/res/layout/fragment_home_stop.xml
  app/src/main/res/layout/walkitem.xml
Labels: FEAT, UI, REFACTOR

#54 [FEAT] : Polyline의 색깔과 너비 수정할 수 있게 수정
  app/build.gradle.kts
  app/src/main/java/com/footprint/app/api/NetWorkInterface.kt
  app/src/main/java/com/footprint/app/services/MyService.kt
  app/src/main/java/com/footprint/app/ui/home/FavoriteAdapter.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFavoriteItemFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeStopFragment.kt
  app/src/main/java/com/footprint/app/ui/home/HomeViewModel.kt
  app/src/main/res/layout/dialog_home_polyline.xml
  app/src/main/res/layout/fragment_home.xml
Labels: FEAT
